### ISSUE TITLE
Publish a more recent build of the fbjni shared object

### ISSUE THREAD

**Issue by GoatHunter** [facebookincubator/fbjni#33]
## Issue description
Hey, 
First, thanks a lot for sharing your well written library in an external repo!

Prior to this repo, we've been using some version of it which was embedded in React Native, and had to
learn its usage from React's code, and now you've given us a good load of examples of best practices.

Anyways, my only question to you is whether you're planning to publish a more recent build of libfbjni.so to bintray's Jcenter, currently we have a frankstein-ish build that uses 0.0.3 java part from Jcenter whereas we build libfbjni.so locally.

If I can help in some manner to make that happen, let me know, I'll glady contribute.
Another side note, it will be helpful if tags were incorporated into the repo denoting each release.

Keep up the awesome work!

Max, Autodesk.

**Comment by dreiss** [comment]
We published 0.0.4 a few weeks ago.  Thanks for the positive feedback!

**Comment by cpsauer** [comment]
Should we close this one down, given that there have been a bunch of recent releases?

**Comment by cortinico** [comment]
Closing as 0.4.0 got released recently
