### ISSUE TITLE
Are there plans to use Android Studio 4.0 Prefab for native dependencies?

### ISSUE THREAD

**Issue by chenfei0928** [facebookincubator/fbjni#35]
I watched the update introduction video of Android Studio 4.0 (https://www.youtube.com/watch?v=f1fHPqAYj5I), which said that there is a new local dependency solution: Prefab (http://goo.gle/2LxLJc0).

Are there plans to use Prefab for Android Studio 4.0 native dependencies?

**Comment by dreiss** [comment]
Yeah, we'll probably do this at some point.

**Comment by passy** [comment]
Very late response, but yes, I'm working on it.

**Comment by passy** [comment]
Done! With 0.1.0, you're now getting prefabs. :)
