### ISSUE TITLE
Is this repo still being maintained?

### ISSUE THREAD

**Issue by erip** [facebookincubator/fbjni#39]
I've been waiting for some engagement on some PRs to fix the build for fbjni and to add Windows support, but haven't had much success. Given that and that the last update was in July, I wanted to inquire about the status of this project. I understand that this is an incubating project, but because PyTorch is relying on this repo I want to ensure that this is neither a dead project nor a project that can only get attention from Facebook employees.

**Comment by passy** [comment]
Hey @erip! Sorry for the frustrating experience. We don't have a good ownership structure for this team. I don't know the internals well enough to sign off on any big changes like yours. Let me see if I can find someone by importing it internally.
