### ISSUE TITLE
Move artifact out of jcenter to mavencentral

### ISSUE THREAD

**Issue by pke** [facebookincubator/fbjni#53]
With jcenter going out of business this repos artifacts should be distributed to another repository (mavencentral?).

**Comment by cpsauer** [comment]
Looks to me like it already is! 

[See https://github.com/facebookincubator/fbjni/commit/e36da744d288714db7bf404c96ec367e689deb01 and https://search.maven.org/artifact/com.facebook.fbjni/fbjni/0.2.2/aar]

I only see old ones on jcenter.

**Comment by pke** [comment]
Cool. Then I will close this.
