### ISSUE TITLE
Can it call the method  in torch ？

### ISSUE THREAD

**Issue by qshian** [facebookincubator/fbjni#56]
I'm very glad to see such a good project！！！
We call a lot of the pytorch model in the java server by rpc api
Can I use this to call pytorch's C + + interface directly ？
How about the performance at  high concurrency？
hope some exampels

**Comment by dreiss** [comment]
PyTorch has Java bindings for loading and running TorchScript models.  There's a demo at https://github.com/pytorch/java-demo .
