### ISSUE TITLE
Is there any example for creating a Hybrid class?

### ISSUE THREAD

**Issue by psionic12** [facebookincubator/fbjni#57]
As I understand about the Hybrid (correct me if I'm wrong), it is a glue to bind an C++ object to a Java object, and is useful to handle C++ lifetime.

But I didn't find any docs about how to use them, so is there any examples?

**Comment by barthap** [comment]
Hi, you can look at the code of [react-native-reanimated](https://github.com/software-mansion/react-native-reanimated/tree/master/android/src/main/cpp) - it's using hybrid classes extensively.

**Comment by psionic12** [comment]
I wrote a example demo on how to import and use fbjni, hope it can help others.
