### ISSUE TITLE
New release? 0.2.3

### ISSUE THREAD

**Issue by mrousavy** [facebookincubator/fbjni#63]
Hey! I'm trying to use `ArrayList<T>` and `HashMap<K, V>` in JNI, but 0.2.2 (current latest release) does not contain those bindings. A week ago a commit landed on master (by @dreiss: https://github.com/facebookincubator/fbjni/commit/f730250ff16424ae7d85550a7aea62a10c7a0a36) that implemented both bindings, can you publish a release for that?

Thanks!

**Comment by mrousavy** [comment]
(cc @mhorowitz)

**Comment by mhorowitz** [comment]
I'm not involved with fbjni releases.  However, you don't need to wait.  There's no harm in redundant bindings, so you can include them in your own code (just use your own namespace).  Later, you can migrate to the standard bindings once a release include them.  As long as the descriptor strings are the same, the behavior should not change.

**Comment by cortinico** [comment]
Closing as we released 0.4.0 on Maven Central recently
