### ISSUE TITLE
Upload version 0.0.3 to Maven Central Repository

### ISSUE THREAD

**Issue by valentinmakov** [facebookincubator/fbjni#65]
Our React Native project requires com.facebook.fbjni:fbjni-java-only:0.0.3 which is currently only available on jcenter. Since jcenter is to be closed, it is crucial for us to be able to download com.facebook.fbjni:fbjni-java-only:0.0.3 from Maven Central Repository. Now it only contains versions 0.0.4 and newer. Meanwhile, 0.0.3 is a dependency required by the latest React Native release (0.64.2)

**Comment by murat-mehmet** [comment]
Same problem here...

**Comment by Bayramito** [comment]
+1 same here

**Comment by ajaysadhu** [comment]
Yup, org.pytorch:pytorch_android_lite:1.9.0 requires com.facebook.fbjni:fbjni-java-only:0.0.3 as well. Is there any migratory process that's planned for earlier packaged versions which are in jcenter() to be moved over to mavencentral() ?

**Comment by FriendlyUser** [comment]
any alternatives here?

**Comment by brentvatne** [comment]
this would be very useful, jcenter is not particularly reliable anymore - it has been down most of the day today

**Comment by anija** [comment]
Same problem...

**Comment by byCedric** [comment]
Another jcenter outage, another day where this would have been super useful

**Comment by Michelalmeidasilva** [comment]
same problem here

**Comment by cortinico** [comment]
> Our React Native project requires com.facebook.fbjni:fbjni-java-only:0.0.3 which is currently only available on jcenter.

Quick update: the mentioned artifact has now been re-uploaded to MavenCentral
https://repo1.maven.org/maven2/com/facebook/fbjni/fbjni-java-only/0.0.3/

@passy we should be good closing this off 👌
