### ISSUE TITLE
`-headers` files are missing in 0.5.0

### ISSUE THREAD

**Issue by CoSNaYe** [facebookincubator/fbjni#86]
## Issue description

Compared with [0.4.0](https://repo.maven.apache.org/maven2/com/facebook/fbjni/fbjni/0.4.0/), the files of [0.5.0 in maven](https://repo.maven.apache.org/maven2/com/facebook/fbjni/fbjni/0.5.0/) don't have `-headers` files.

And it causes some libraries installation failed. 
eg. `react-native-mmkv@2.5.1` [gradle](https://github.com/mrousavy/react-native-mmkv/blob/v2.5.1/android/build.gradle)

**Comment by cortinico** [comment]
Duplicates of #85
