### ISSUE TITLE
Support 16KB page size devices

### ISSUE THREAD

**Issue by jstewart5000** [facebookincubator/fbjni#97]
#### Description:
In Android 15 [support for 16KB page sizes has been announced](https://developer.android.com/about/versions/15/behavior-changes-all#16-kb).

However,`libfbjni.so` ELF segments are not aligned (`UNALIGNED (212)`) using 16 KB ELF alignment. This results in runtime crash when loading `libfbjni.so` on emulator that is configured to use 16KB page size:
```
/tmp/my_apk_out/lib/arm64-v8a/libfbjni.so: UNALIGNED (212)
```

#### How To Reproduce:

- This can also be verified by preparing and running alignment.sh script [as described in the documentation](https://developer.android.com/guide/practices/page-sizes#test).
- The solution is to compile `libfbjni.so` with 16KB ELF alignment as described [here](https://developer.android.com/guide/practices/page-sizes#compile-16-kb-alignment).

##### Environment
- Android Emulator 35.1.4
- Google APIs Experimental 16k Page Size arm64 System Image - API Level VanillaIceCream - Revision 1

**Comment by cortinico** [comment]
cc @alanleedev

**Comment by brocollie08** [comment]
https://github.com/facebookincubator/fbjni/pull/98 this should do it

**Comment by brocollie08** [comment]
@cortinico would it be possible to cut a release for this so we can start pulling the artifact from maven?

**Comment by cortinico** [comment]
Yup this will be included in 0.7.0:
- https://github.com/facebookincubator/fbjni/pull/100

**Comment by cortinico** [comment]
This has been shipped in 0.7.0:
https://github.com/facebookincubator/fbjni/releases/tag/v0.7.0
